spring:
  datasource:
    url: jdbc:mysql://localhost:3307/quiz-springboot?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: root
    password: Duyngan96
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: [classpath:META-INF/resources/, file:src/main/resources/, file:src/main/resources/static/, file:src/main/resources/static/assets/, classpath:/public/]
    resources.cache.period: 0

  jpa:
    generate-ddl: true
    show-sql: true
